# Default configuration template

# Data sources configuration
sources:
  etf_com:
    enabled: true
    priority: 1
    rate_limit: 5
    cache_ttl: 86400
    
  yahoo_finance:
    enabled: true
    priority: 2
    rate_limit: 10
    cache_ttl: 3600

# Trading cost thresholds
cost_thresholds:
  spread:
    warning: 0.0020  # 0.20%
    alert: 0.0050    # 0.50%
  
  market_impact:
    warning: 0.0025  # 0.25%
    alert: 0.0050    # 0.50%
    
  total_cost:
    warning: 0.0050  # 0.50%
    alert: 0.0100    # 1.00%

# Premium/Discount monitoring
premium_discount:
  normal_range: 0.0025  # ±0.25%
  warning_level: 0.0050 # ±0.50%
  alert_level: 0.0100   # ±1.00%

# Market maker quality thresholds
market_maker:
  quote_presence:
    minimum: 0.95    # 95%
    target: 0.98     # 98%
    
  spread_stability:
    minimum: 0.80    # 80%
    target: 0.90     # 90%
    
  price_continuity:
    minimum: 0.90    # 90%
    target: 0.95     # 95% 